@url = http://localhost:5032

@epicId = b7f05c08-5178-45bc-ab0c-afc41d1d289e
@epicId2 = ccdf6a07-8c47-47d8-be4c-4e07376c15aa

###
GET {{url}}/epics

###
GET {{url}}/epics/{{epicId}}

###
POST {{url}}/epics
Content-Type: application/json

{
    "name": "Test1",
    "description": "TestDescription",
    "acceptanceCriteria": "TestAcceptanceCritera"
}

###
PUT {{url}}/epics/{{epicId}}
Content-Type: application/json

{
    "name": "TestUpdated",
    "description": "TestDescriptionUpdated",
    "acceptanceCriteria": "TestAcceptanceCriteraUpdated",
    "status": "InProgress"
}

###
DELETE {{url}}/epics/{{epicId}}