@url = http://localhost:5032

@epicId = 1473c13c-8fb2-4343-857c-30d9229a6abb
@epicId2 = b9bdff09-c583-4758-ace2-7dde3f59e446

###
GET {{url}}/epics

###
GET {{url}}/epics/{{epicId}}

###
POST {{url}}/epics
Content-Type: application/json

{
    "name": "Test1",
    "description": "TestDescription",
    "acceptanceCriteria": "TestAcceptanceCritera"
}

###
PUT {{url}}/epics/{{epicId}}
Content-Type: application/json

{
    "name": "TestUpdated",
    "description": "TestDescriptionUpdated",
    "acceptanceCriteria": "TestAcceptanceCriteraUpdated",
    "status": "InProgress"
}

###
DELETE {{url}}/epics/{{epicId}}